CREATE TABLE IF NOT EXISTS Links(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    gameId INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    TYPE TEXT,
    path TEXT,
    FOREIGN KEY (gameId) REFERENCES games(id)
)